import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryClientProvider } from "@tanstack/react-query";
import queryClient from "@/services/queryClient";
import Setup from "@/services/setup";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BD Tech Center",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Setup>
          {children}
        </Setup>
      </body>
    </html>
  );
}
